name: Build_CI_Vue_Dev

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md"
      - "**/dependabot.yml"
      - ".github/workflows/develop_CD.yml"
      - ".github/workflows/main_CD.yml"
    branches:
      - develop

concurrency: develop_CI

jobs:
  build-ci:
    name: "Build and CI Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: ".nvmrc"

      - name: Cypress CI Run
        uses: cypress-io/github-action@v6
        with:
          command-prefix: "--"
          build: npm run build:development
          start: npm run serve
          wait-on: "http://localhost:3000"
          config-file: cypress.config.ci.js

  automerge:
    needs: build-ci
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
