name: Deploy_To_Azure_Blobs_Dev

on:
  push:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md" # don't run on README.md file updates anywhere in repo
      - "**/dependabot.yml"
    branches:
      - develop
  schedule:
    - cron: "24 04 * * *" # 0424am daily

env:
  AZURE_CREDENTIALS: ${{ secrets.DEV_AZURE_CREDENTIALS }}
  STORAGE_KEY: ${{ secrets.DEV_STORAGE_KEY }}

jobs:
  should_run:
    uses: IATI/.github/.github/workflows/should_run.yaml@main

  deploy:
    needs: should_run
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Run build
        run: |
          npm run build:development

      - name: Create robots.txt
        run: |
          echo -e 'User-agent: *\nDisallow: /\n' > dist/robots.txt

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        env:
          STORAGE_NAME: sadatastoresearchdev
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.STORAGE_NAME }} -d '$web' -s dist/

  integration-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Cypress CI Run
        uses: cypress-io/github-action@v2
        with:
          wait-on: "https://dev-datastore.iatistandard.org"
          config-file: cypress/envs/cypress.int.development.json
