name: Build_Vue_Dev

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
      - '.github/workflows/develop_CD.yml'
      - '.github/workflows/main_CD.yml'
    branches:
      - develop

concurrency: develop_CI

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: Run build
        run: |
          npm run build

      - name: Test end-to-end
        run: |
          npm install --global http-server &&
          http-server dist &
          sleep 10 &&
          curl http://localhost:8080 &&
          npm run cy:run-ci

  automerge:
      needs: build
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: write
      steps:
        - uses: fastify/github-action-merge-dependabot@v3.0.2
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
