name: Deploy_To_Azure_Blobs_Prod

on:
  release:
    types: [published]

env:
  STORAGE_ACCOUNT_NAME: sadatastoresearchprod
  STORAGE_ACCOUNT_KEY: ${{ secrets.PROD_STORAGE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Create production index.html
        run: |
          mv index.prod.html index.html

      - name: Run build
        run: |
          npm run build:production

      - name: Create robots.txt
        run: |
          echo -e 'User-agent: *\nDisallow:\nSitemap: https://datastore.iatistandard.org/sitemap-index.xml\n' > dist/robots.txt

      - name: Upload to blob storage
        uses: azure/CLI@v2
        with:
          azcliversion: 2.34.0
          inlineScript: |
            az storage blob upload-batch \
            --overwrite true \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --account-key ${{ env.STORAGE_ACCOUNT_KEY }} \
            -d '$web' \
            -s dist/

  integration-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cypress CI Run
        uses: cypress-io/github-action@v6
        with:
          wait-on: "https://datastore.iatistandard.org"
          config-file: cypress.config.prod.js
