name: Deploy_To_Azure_Blobs_Prod

on:
  release:
    types: [published]

env:
  AZURE_CREDENTIALS: ${{ secrets.PROD_AZURE_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: Run build
        run: |
          npm run build:production

      - name: Create robots.txt
        run: |
          echo -e 'User-agent: *\nDisallow:\n' > dist/robots.txt

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        env: 
          STORAGE_NAME: sadatastoresearchprod
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.STORAGE_NAME }} --auth-mode key -d '$web' -s dist/
